### ISSUE TITLE
link RtlGenRandom

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#318]
rule idea:

```yaml
# generated using capa explorer for IDA Pro
rule:
  meta:
    name: link RtlGenRandom
    namespace: <PRNG>
    scope: function
  features:
    - and:
      - match: link function at runtime
      - string: SystemFunction036
      - optional:
        - string: advapi32.dll
        - string: Advapi32.dll
        - characteristic: indirect call
```
