### ISSUE TITLE
detect tiny encryption algorithm (TEA) block cipher

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa-rules#532]
maybe:
```yaml
...
- and:
  - number:  0xC6EF372 = TEA sum
  - or:
    - number: 0x9E3779B9 = TEA delta
    - number: 0x61C88647 = TEA delta
...
```

references:
- https://en.wikipedia.org/wiki/Tiny_Encryption_Algorithm
- https://twitter.com/codexgigassys/status/765743255917125632
