### ISSUE TITLE
hash data with CRC32

### ISSUE THREAD

**Issue by as0ni** [mandiant/capa-rules#617]
## Summary

**Rule name:** hash data with CRC32

This rule hit on a sample of interest in capa v3, but I noticed capa v4 missed it due to a change in this rule. 

## Examples

**SHA-256:** 861bc212241bcac9f8095c8de1b180b398057cbb2d37c9220086ffaf24ba9e08

Function at 0x405846 implements CRC32.

## Possible improvements

Add `number: 0xEDB88320` as shown below. The current rule splits this constant into 0x8320 and 0xEDB8. I expected this to still work, but perhaps the number instruction feature only looks at an operand in its entirety (i.e., not part of an operand)? 

```
rule:
  meta:
    name: hash data with CRC32
    namespace: data-manipulation/checksum/crc32
    authors:
      - moritz.raabe@mandiant.com
    scope: function
    mbc:
      - Data::Checksum::CRC32 [C0032.001]
    examples:
      - 2D3EDC218A90F03089CC01715A9F047F:0x403CBD
      - 7D28CB106CB54876B2A5C111724A07CD:0x402350  # RtlComputeCrc32
      - 7EFF498DE13CC734262F87E6B3EF38AB:0x100084A6
  features:
    - or:
      - and:
        - number: 1 = bits in a byte
        - instruction:
          - description: is bit set?
          - mnemonic: test
          - operand[1].number: 1
        - instruction:
          - mnemonic: shr
          - number: 1
        - instruction:
          - mnemonic: xor
          - operand[1].number: 0xEDB88320
      - and:
        - or:
            - and:
                - number: 0x8320
                - number: 0xEDB8
            - number: 0xEDB88320
        - characteristic: nzxor
      - api: RtlComputeCrc32
      - bytes: 00 00 00 00 96 30 07 77 2C 61 0E EE BA 51 09 99 19 C4 6D 07 8F F4 6A 70 35 A5 63 E9 A3 95 64 9E = crc32_tab
```    

## Additional context

![image](https://user-images.githubusercontent.com/8812157/188199534-2a4e4599-facd-4f96-b8f7-63bf6416d1b2.png)

FYI this rule is also referenced here as an example: https://github.com/mandiant/capa-rules/blob/master/doc/format.md
