### ISSUE TITLE
resolve Microsoft.Win32.Win32Native to execute native Windows APIs in .NET

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa-rules#876]
```yaml
- and:
  - api: System.Reflection.Assembly::GetType
  - string: "Microsoft.Win32.Win32Native"
```
